# Chapter-6 Arrays

This notebook contains the sample source code explained in the book *Hands-On Julia Programming, Sambit Kumar Dash, 2021, bpb Publications. All Rights Reserved*.

In [107]:
using Pkg
pkg"activate ."
pkg"instantiate"

  Activating project at `C:\Users\WoU_AI_ML`


## 6.1 Introduction

Arrays are used extensively as they are simple and have a memory layout that can store objects on contiguous addresses. Most importantly they can be used by other datastructure implementations. 

### Container

In [108]:
a = []

Any[]

In [109]:
push!(a, 5)

1-element Vector{Any}:
 5

In [110]:
push!(a, 5, 6, 7, 8)

5-element Vector{Any}:
 5
 5
 6
 7
 8

In [111]:
pop!(a)

8

In [112]:
length(a)

4

In [113]:
isempty(a)

false

In [114]:
empty!(a)

Any[]

In [115]:
isempty(a)

true

In [116]:
push!(a, 1, 2, 3, 4, 5)

5-element Vector{Any}:
 1
 2
 3
 4
 5

In [117]:
popfirst!(a)

1

In [118]:
a

4-element Vector{Any}:
 2
 3
 4
 5

In [119]:
pushfirst!(a, 1)

5-element Vector{Any}:
 1
 2
 3
 4
 5

## 6.2 Dimensions

Arrays are allocated as a linear chunk of memory. They can further reshaped for indexing and access in anyways desirable while keeping the original row major ordering intact.

![image](cube.png)

In [120]:
a = reshape(collect(1:24), 4, 3, 2)

4×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  5   9
 2  6  10
 3  7  11
 4  8  12

[:, :, 2] =
 13  17  21
 14  18  22
 15  19  23
 16  20  24

In [121]:
ndims(a)

3

In [122]:
size(a)

(4, 3, 2)

In [123]:
size(a, 3)

2

## 6.3 Indexing

Considered as the primary means of accessing one or more elements of an array. Variety of indexing schemes exist for arrays beyond simple integer scalars. 

### Scalars

In [124]:
a = reshape(collect(1:24), 4, 3, 2, 1)

4×3×2×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1  5   9
 2  6  10
 3  7  11
 4  8  12

[:, :, 2, 1] =
 13  17  21
 14  18  22
 15  19  23
 16  20  24

In [125]:
a[1, 2, 1, 1]

5

### Ranges

In [126]:
a[:, 1, 1, 1]

4-element Vector{Int64}:
 1
 2
 3
 4

In [127]:
a[2:3, 1, 1, 1]

2-element Vector{Int64}:
 2
 3

In [128]:
a[1:2:3, 1, 1, 1]

2-element Vector{Int64}:
 1
 3

In [129]:
a[1:2:3, 1:2:3, 1, 1]

2×2 Matrix{Int64}:
 1   9
 3  11

### Vectors 

In [130]:
a[1:2:3, 1:2:3, [1], [1]]

2×2×1×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1   9
 3  11

In [131]:
a[1:2:3, [1; 3], 1, 1]

2×2 Matrix{Int64}:
 1   9
 3  11

In [132]:
a[1:2:3, [1, 3], 1, 1]

2×2 Matrix{Int64}:
 1   9
 3  11

In [133]:
b = a[1:2:3, [1 3], 1, 1]

2×1×2 Array{Int64, 3}:
[:, :, 1] =
 1
 3

[:, :, 2] =
  9
 11

In [134]:
a[:, [2], [1], [1]]

4×1×1×1 Array{Int64, 4}:
[:, :, 1, 1] =
 5
 6
 7
 8

In [135]:
a[[1 2; 3 4], [2], [1], [1]]

2×2×1×1×1 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 5  6
 7  8

### Linear Index

Accessing the array as a single element linear index as if the array is flattened to a single dimension vector. 

In [136]:
a = reshape(collect(1:6), (2, 3))

2×3 Matrix{Int64}:
 1  3  5
 2  4  6

In [137]:
a[5]

5

In [138]:
a[1, 3]

5

In [139]:
LinearIndices(a)

2×3 LinearIndices{2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}:
 1  3  5
 2  4  6

### Cartesian Index

Providing indices in each dimension.

In [140]:
A = reshape(collect(1:6), 3, 2)

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

In [141]:
ci = CartesianIndices(A)

CartesianIndices((3, 2))

### Boolean Index

In [142]:
x = reshape(collect(1:16), 4, 4)

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

In [143]:
filter = map(ispow2, x)

4×4 Matrix{Bool}:
 1  0  0  0
 1  0  0  0
 0  0  0  0
 1  1  0  1

In [144]:
x[filter]

5-element Vector{Int64}:
  1
  2
  4
  8
 16

In [145]:
x[[false, true, true, false], :]

2×4 Matrix{Int64}:
 2  6  10  14
 3  7  11  15

### Assignment 

In [146]:
a = reshape(collect(1:24), 4, 3, 2, 1)
a[:, 2, 1, 1] = fill(25, 4)

4-element Vector{Int64}:
 25
 25
 25
 25

In [147]:
a

4×3×2×1 Array{Int64, 4}:
[:, :, 1, 1] =
 1  25   9
 2  25  10
 3  25  11
 4  25  12

[:, :, 2, 1] =
 13  17  21
 14  18  22
 15  19  23
 16  20  24

### Special Indices

`begin` and `end` keywords can be used as indices.  

In [148]:
a = reshape(collect(1:24), 4, 3, 2, 1)
a[:, begin, 2, 1], a[:, begin+1, 2, 1]

([13, 14, 15, 16], [17, 18, 19, 20])

In [149]:
a[end, :, 2, 1], a[end-1, :, 2, 1]

([16, 20, 24], [15, 19, 23])

### Interface

The array indices may not start from 1 and end at the highest value. `firstindex` and `lastindex` help find the valid index range. 

In [150]:
firstindex(a)

1

In [151]:
lastindex(a)

24

In [152]:
lastindex(a, 1)

4

In [153]:
lastindex(a, 2)

3

In [154]:
lastindex(a, 3)

2

In [155]:
lastindex(a, 4)

1

## 6.4 Slicing

Accessing a portion of an array as an a standalone array. Normally, slicing operations allocate new arrays. 

In [156]:
a = reshape(collect(1:9), 3, 3)

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [157]:
a[:, 1]

3-element Vector{Int64}:
 1
 2
 3

In [158]:
a[1, :]

3-element Vector{Int64}:
 1
 4
 7

In [159]:
a[1, 2:3]

2-element Vector{Int64}:
 4
 7

In [160]:
b = a[1:2, :]

2×3 Matrix{Int64}:
 1  4  7
 2  5  8

In [161]:
b[1, 2] = 10

10

In [162]:
b

2×3 Matrix{Int64}:
 1  10  7
 2   5  8

In [163]:
a

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [164]:
v = @view a[1:2, :]

2×3 view(::Matrix{Int64}, 1:2, :) with eltype Int64:
 1  4  7
 2  5  8

In [165]:
v[1, 2] = 10

10

In [166]:
v

2×3 view(::Matrix{Int64}, 1:2, :) with eltype Int64:
 1  10  7
 2   5  8

In [167]:
a

3×3 Matrix{Int64}:
 1  10  7
 2   5  8
 3   6  9

## Broadcasting

Ability to reflect one array or collection over the other element wise (can be row or column wise as well) while applying an operation on them.  

In [168]:
a = reshape(collect(1:9), 3, 3)

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [169]:
b = reshape(collect(9:-1:1), 3, 3)

3×3 Matrix{Int64}:
 9  6  3
 8  5  2
 7  4  1

In [170]:
a + b

3×3 Matrix{Int64}:
 10  10  10
 10  10  10
 10  10  10

In [171]:
broadcast(*, a, b)

3×3 Matrix{Int64}:
  9  24  21
 16  25  16
 21  24   9

In [172]:
a .* b

3×3 Matrix{Int64}:
  9  24  21
 16  25  16
 21  24   9

In [173]:
a = reshape(collect(1:9), 3, 3)

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [174]:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [175]:
a .+ b

3×3 Matrix{Int64}:
 2  6  10
 3  7  11
 4  8  12

In [176]:
b = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [177]:
a .+ b

3×3 Matrix{Int64}:
 2  5   8
 4  7  10
 6  9  12

In [178]:
broadcast(string, ("one","two","three","four"), ": ", 1:4)

4-element Vector{String}:
 "one: 1"
 "two: 2"
 "three: 3"
 "four: 4"

In [179]:
string.(("one","two","three","four"), ": ", 1:4)

4-element Vector{String}:
 "one: 1"
 "two: 2"
 "three: 3"
 "four: 4"

### Performance

Does not store intermediate values so can be lesser allocations and better performing. `repeat` takes a block of an array and duplicates it in each dimension.  

In [180]:
v = [1, 2]

2-element Vector{Int64}:
 1
 2

In [181]:
repeat(v, 2, 3) #Repeats twice in dim 1 and thrice in dim 2. 

4×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2

Now, simulating the broadcast in the previous example with repeat. 

In [182]:
a + repeat(b, 1, 3)

3×3 Matrix{Int64}:
 2  5   8
 4  7  10
 6  9  12

### broadcast vs. map

broadcast will take care of dimension dissimilarities gracefully by repeating. However, `map` will stop at the lower dimension. 

In [183]:
a

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [184]:
b

3-element Vector{Int64}:
 1
 2
 3

In [185]:
map(+, a, b)

3-element Vector{Int64}:
 2
 4
 6

## 6.6 Reduction

Providing summary of array elements in one or more dimensions. Similar to group by clauses of databases. 

In [186]:
a = reshape(collect(1:16), (2, 2, 2, 2))

2×2×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3
 2  4

[:, :, 2, 1] =
 5  7
 6  8

[:, :, 1, 2] =
  9  11
 10  12

[:, :, 2, 2] =
 13  15
 14  16

In [187]:
reduce(+, a)

136

### Associativity

Operator precedence can play a significant role on the results obtained by the reduce operation. 

In [188]:
foldl(=>, [1, 2, 3, 4])

((1 => 2) => 3) => 4

In [189]:
foldr(=>, [1, 2, 3, 4])

1 => (2 => (3 => 4))

In [190]:
reduce(=>, [1, 2, 3, 4])

((1 => 2) => 3) => 4

In [191]:
foldl(-, [1, 2, 3, 4])

-8

In [192]:
foldr(-, [1, 2, 3, 4])

-2

In [193]:
reduce(-, [1, 2, 3, 4])

-8

### Map and reduce

`map` and `reduce` method in one function call. 

In [194]:
mapreduce(x->x*x, +, [1, 2, 3, 4])

30

### Slices

map and reduce operation on slice of an array. 

In [195]:
a = reshape(collect(1:16), 2, 2, 2, 2)
mapslices(sum, a, dims=[1, 2])

1×1×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 10

[:, :, 2, 1] =
 26

[:, :, 1, 2] =
 42

[:, :, 2, 2] =
 58

## 6.7 Abstract Array Types

Abstract arrays provide the array like access interfaces for derived classes to implement. `Array` concrete type also governs the internal storage of elements. One can implement an array type of her own, that is efficient on storage, yet behaves like an array. `MyIdentity` is an identity matrix implemented with only size of matrix information. 1s and 0s are not stored. 

In [196]:
struct MyIdentity{T} <: AbstractMatrix{T}
    l::Int
end

Base.size(m::MyIdentity)=(m.l, m.l)
Base.size(m::MyIdentity, d)=(d == 1 || d == 2) ? m.l : error("Invalid dimensions")

function Base.getindex(m::MyIdentity{T}, i, j) where {T}
    1 <= i <= m.l && 1 <= j <= m.l || error("Invalid indices")
    i == j && return one(T)
    return zero(T)
end

In [197]:
a = MyIdentity{Int}(3)

3×3 MyIdentity{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [198]:
a[1, 2]

0

In [199]:
a = MyIdentity{Float32}(3)

3×3 MyIdentity{Float32}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [200]:
size(a)

(3, 3)

In [201]:
size(a, 1)

3

In [202]:
length(a)

9

In [203]:
similar(a)

3×3 Matrix{Float32}:
 4.544f-41      9.55089f-38  7.12595f-33
 0.0            7.2f-43      0.0
 2.36943f-38  NaN            2.697f-29

In [204]:
IndexStyle(typeof(a))

IndexCartesian()

In [205]:
a[5] # Linear Indexing

1.0f0

In [206]:
a*[1,2,3]

3-element Vector{Float32}:
 1.0
 2.0
 3.0

## 6.8 Sparse Arrays

### Sparse Vector Storage

```
# This is the internal definition of SparseVector in Julia
# It's stated here for refernce only. DO NOT RUN this code. 

struct SparseVector{Tv,Ti<:Integer} <: AbstractSparseVector{Tv,Ti}
    n::Int              # Length of the sparse vector
    nzind::Vector{Ti}   # Indices of stored values
    nzval::Vector{Tv}   # Stored values, typically nonzeros
end
```

In [207]:
using SparseArrays
I = [1, 4, 3, 5]
V = [1, 2, -5, 3]
R = sparsevec(I,V)

5-element SparseVector{Int64, Int64} with 4 stored entries:
  [1]  =  1
  [3]  =  -5
  [4]  =  2
  [5]  =  3

In [208]:
findnz(R)

([1, 3, 4, 5], [1, -5, 2, 3])

### Sparse Matrix Storage

```
# This is the internal definition of SparseMatrixCSC in Julia
# It's stated here for refernce only. DO NOT RUN this code.

struct SparseMatrixCSC{Tv,Ti<:Integer} <: AbstractSparseMatrix{Tv,Ti}
    m::Int                  # Number of rows
    n::Int                  # Number of columns
    colptr::Vector{Ti}      # Column j is in 
                            #      colptr[j]:(colptr[j+1]-1)
    rowval::Vector{Ti}      # Row indices of stored values
    nzval::Vector{Tv}       # Stored values, typically nonzeros
end
```

In [209]:
I = [1, 4, 3, 5]
J = [4, 7, 18, 9]
V = [1, 2, -5, 3]

S = sparse(I, J, V)

5×18 SparseMatrixCSC{Int64, Int64} with 4 stored entries:
⠀⠈⠀⡀⠀⠀⠀⠀⠠
⠀⠀⠀⠀⠁⠀⠀⠀⠀

In [210]:
findnz(S)

([1, 4, 5, 3], [4, 7, 9, 18], [1, 2, 3, -5])

In [211]:
S[1, 2]

0

In [212]:
size(S)

(5, 18)